# This is a basic workflow to help you get started with Actions

name: CPR V2

# Controls when the action will run. 
on:
  schedule:
    - cron: '1/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create file
        run: date >> testfile.txt
      - name: Create PR
        uses: peter-evans/create-pull-request@v3.9.2
        id: cpr
        with: 
          token: ${{ secrets.PAT }}
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
