# This is a basic workflow to help you get started with Actions

name: Merge Content PRs

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo;
            const issues = await github.search.issuesAndPullRequests({q: `label:ContentSyncAutoMerge+repo:${repo}`});
            issues.map(function(issue) {
              const fullIssue = await github.pulls.get({owner, repo, pull_number: issue.number});
              console.log(fullIssue);
            });
