
name: Merge Content PRs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prQuery = `query { 
              search(query:"label:ContentSyncAutoMerge is:open repo:ezcater/ezcater_contentful-ts", type: ISSUE, first: 10) {
                nodes {
                  ...on PullRequest {
                    title
                    commits(last: 2) {
                      nodes {
                        commit {
                          statusCheckRollup {
                            state
                          } // statusCheckRollup
                          status {
                            id
                          } //status
                        } // commit
                      } // commits nodes       
                    }// commits
                 } // PullRequest
                } // search Nodes
              } // search
             } // query
            const result = await github.graphql(query, {});
            console.log(results);
