
name: Merge Content PRs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prQuery = `query { 
              search(query:"label:ContentSyncAutoMerge is:open repo:drapergeek/actions-playing", type: ISSUE, first: 10) {
                nodes {
                  ...on PullRequest {
                    title
                    id
                    commits(last: 1) {
                      nodes {
                        commit {
                          statusCheckRollup {
                            state
                          } # statusCheckRollup
                          status {
                            id
                          } #status
                        } # commit
                      } # commits nodes       
                    } # commits
                 } # PullRequest
                } # search Nodes
              } # search
             } # query`;
            const prResult = await github.graphql(prQuery, {});
            const prs = prResult.search.nodes.filter(function (node) {
              console.log(node);
              try {
                // return node.commits.nodes[0].commit.statusCheckRollup.state === "SUCCESS";
                return true;
              } catch {
                return false;
              }            
            });
            console.log('merging these prs %o', prs);
            for (const pr of prs) {
              const prMutation = `mutation mergePullRequest($input: MergePullRequestInput!) {
                mergePullRequest(input: $input) {
                  pullRequest {
                    mergedAt
                 }
               }  
              }`;
              console.log("Merging PR %o", pr);
              const result = await github.graphql(prMutation, {"input": {"pullRequestId": pr.id}})
              console.log(result);
            };
